<?php
/**
 * @file
 * Code for the OS2Web Kontaktblok feature.
 */

include_once 'os2web_contact.features.inc';

/**
 * Helper function to provide a os2web_contact_contact node for views.
 *
 * return int nid of block node.
 */
function os2web_contact_get_block() {
  $result = 0;
  $menu = menu_get_active_trail();
  while ($item = array_pop($menu)) {
    $path = explode('/', $item['link_path']);
    if ($path[0] === 'taxonomy' && $path[1] === 'term') {
      $ent = taxonomy_term_load($path[2]);
      $field = field_get_items('taxonomy_term', $ent, 'field_node_reference_os2web_contact_contact');
    }
    elseif ($path[0] === 'node') {
      $ent = node_load($path[1]);
      $field = field_get_items('node', $ent, 'field_node_reference_os2web_contact_contact');
    }
    elseif ($path[1] == 0) {
      $node = menu_get_object();
      $field = field_get_items('node', $node,'field_node_reference_os2web_contact_contact');
    }
    if (isset($field[0]['nid'])) {
      $result = $field[0]['nid'];
      break;
    }
  }
  return $result;
}

/**
 * Implements hook_os2web_help().
 */
function os2web_contact_os2web_help($sections) {

  // Content types.
  $sections['contenttype'] = t('<p><b>Contact block:</b> Add a <a href="@url" target="_blank">contact block</a> that can be used on any page. Contact blocks are blocks that will be shown next to the main content of a page. Add a contact for each department you have on your site. If a contact block is wanted on a specific page, it can be added by editing the page itself.<br />Contact blocks includes opening hours.</p>', array('@url' => url('node/add/os2web-contact-contact')));
  return $sections;
}
